name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        users: actions/checkout@v4

      - name: Set up Go
        users: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Force Failure
        run: (exit 1)

      - name: Go version
        run: go version


